### ISSUE TITLE
[Question] About File Size after update.

### ISSUE THREAD

**Issue by ghost** [KingTheGuy/i_have_hands#1]
Hello,

I have a question, after the update, this mod is now 11,3MB big, and I see that, after update, there is now the repo-assets folder, that has a .gif file that gave this mod that size increase, but is there a need for that file in the downloaded mod?

**Comment by KingTheGuy** [comment]
yea my bad, i keep rushing publishing and sometimes zip un-needed things.

uploaded the right zip. look for 1.0.5[fixed]

**Comment by ghost** [comment]
@KingTheGuy 

See it already.

Thank you.

And nice mod.
